server:
  port: 9001

spring:
  application:
    name: dubbo

  dubbo:
    server: true
    application:
      name: provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: cn.mirror6.provider.service
